## Understanding Coding with Python
### Convolution: 1D operation with python (Numpy/Scipy)

One Dimensional Convolutional Operation
+ let
    + x is kernel : x[i] = {3,4,5}
    + h is image  : h[i] = {2,1,0}
    


In [1]:
import numpy as np

h = [2,1,0]
x = [3,4,5]

y = np.convolve(x,h)
y

array([ 6, 11, 14,  5,  0])

#### Three Methods to apply kernel on matrix

+ with padding (full)
+ with padding (same)
+ without padding (valid)

#### 1. With Padding (full)

+ x[i] = [6,2]
+ h[i] = [1,2,5,4]

+ Invert the filter x

In [4]:
import numpy as np

x = [6,2]
h = [1,2,5,4]
# because of the zero padding, the final dimension of the array is bigger
y = np.convolve(x, h, "full")
y

array([ 6, 14, 34, 34,  8])

#### 2. With Padding (same)

+ add zero to left only
+ ie, the first four step of "full" process

In [5]:
import numpy as np

x = [6,2]
h = [1,2,5,4]

y = np.convolve(x,h, "same")
y

array([ 6, 14, 34, 34])

#### 3. Withput Padding (valid)

+ This method is used when we needed Dimensionality Reduction
+ There will be no Padding

In [6]:
import numpy as np

x = [6,2]
h = [1,2,5,4]

y = np.convolve(x,h, "valid")
y

array([14, 34, 34])

### Convolution: 2D Operation with Python (Numpy/Scipy)

The 2D convolution operation is defined as:

<font size="4">$$ I'= \sum\limits_{u,v} I(x-u,y-v)g(u,v) $$ </font>

$
I=
\begin{bmatrix}
     255          & 7      & 3     \\
     212          & 240    & 4     \\
     218          & 216    & 230
\end{bmatrix}
\\
$ 

$
g=
\begin{bmatrix}
     -1          & 1      
\end{bmatrix}
\\
$ 

let I be Image and g be the Filter, code will give


In [7]:
from scipy import signal as sg

In [8]:
I= [[255,   7,  3],
    [212, 240,  4],
    [218, 216, 230],]

g= [[-1, 1]]

print("Without Zero Padding:")
print(sg.convolve(I,g, "valid"))

Without Zero Padding:
[[248   4]
 [-28 236]
 [  2 -14]]


In [9]:
print("With Zero Padding:")
print(sg.convolve(I,g))

With Zero Padding:
[[-255  248    4    3]
 [-212  -28  236    4]
 [-218    2  -14  230]]


In [11]:
print("With zero Padding(full):")
print(sg.convolve(I,g, "full"))

With zero Padding(full):
[[-255  248    4    3]
 [-212  -28  236    4]
 [-218    2  -14  230]]


In [12]:
print("With zero Padding(same):")
print(sg.convolve(I,g, "same"))

With zero Padding(same):
[[-255  248    4]
 [-212  -28  236]
 [-218    2  -14]]


 when the filter is
 + h= [ [-1  1] , [2   3] ]

In [13]:
from scipy import signal as sg

I= [[255,   7,  3],
    [212, 240,  4],
    [218, 216, 230],]

g= [[-1,  1],
    [ 2,  3],]

print("With zero Padding(full):")
print(sg.convolve(I,g, "full"))

print("With zero Padding(same):")
print(sg.convolve(I,g, "same"))

print("Without zero Padding(valid):")
print(sg.convolve(I,g, "valid"))

With zero Padding(full):
[[-255  248    4    3]
 [ 298  751  263   13]
 [ 206 1118  714  242]
 [ 436 1086 1108  690]]
With zero Padding(same):
[[-255  248    4]
 [ 298  751  263]
 [ 206 1118  714]]
Without zero Padding(valid):
[[ 751  263]
 [1118  714]]
