# Convolution
### Coding with Tensorflow

+ Numpy is great because of the high optimized matrix operations in a backend using C/C++

+ Tensorflow does the same work, But insted of returning to python eerytime,
    + it will create all operations in th eform of graphs
    + then execute them once with highly optimized backend

Let two Tensors
+ 3x3 filter (4D tensor = [3,3,1,1] = [width, height, channels, no. of filters])

+ 10x10 image (4D tensor = [1,10,10,1] = [batch size, width, height, no of channels])

The output size with zero padding "same" will be
+ the same as input = 10x10

The output size without zero padding "valid" will be
+ input size - kernal dimension + 1 = 10-3+1 = 8

In [2]:
import tensorflow as tf

#Building Graph
input = tf.Variable(tf.random_normal([1,10,10,1]))
filter = tf.Variable(tf.random_normal([3,3,1,1]))

op1 = tf.nn.conv2d(input,filter,strides = [1,1,1,1], padding = "VALID")
op2 = tf.nn.conv2d(input,filter,strides = [1,1,1,1], padding = "SAME")

In [3]:
op1

<tf.Tensor 'Conv2D:0' shape=(1, 8, 8, 1) dtype=float32>

In [4]:
op2

<tf.Tensor 'Conv2D_1:0' shape=(1, 10, 10, 1) dtype=float32>

In [6]:
# initialization and session
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    result_1 = sess.run(op1)
    print(result_1)
    
    result_2 = sess.run(op2)
    print(result_2)


[[[[  1.2087505 ]
   [ -0.36132336]
   [ -6.8565564 ]
   [  3.5031638 ]
   [  2.685858  ]
   [  2.7469137 ]
   [-10.28799   ]
   [  4.238157  ]]

  [[  1.4035294 ]
   [  0.26944804]
   [  3.8543913 ]
   [ -0.7110522 ]
   [-11.860386  ]
   [  3.0347514 ]
   [  1.4143293 ]
   [ -7.136351  ]]

  [[ -4.0639896 ]
   [  0.74945635]
   [ -2.913282  ]
   [  2.597951  ]
   [ -1.7814432 ]
   [  4.699813  ]
   [  0.81604195]
   [ -3.771521  ]]

  [[ -2.7887988 ]
   [ -1.3327476 ]
   [ -4.897997  ]
   [  0.7273413 ]
   [  0.81232613]
   [ -1.4280488 ]
   [ -3.4469957 ]
   [ -0.0555592 ]]

  [[ -0.46254724]
   [ -0.47039828]
   [  0.45643827]
   [  0.8615178 ]
   [  2.7886739 ]
   [  3.6153595 ]
   [ -0.87505174]
   [ -1.1243367 ]]

  [[  0.035703  ]
   [  1.2247715 ]
   [  2.2450721 ]
   [  3.5613961 ]
   [  2.567297  ]
   [ -4.7126164 ]
   [  0.5837722 ]
   [ -5.026825  ]]

  [[ -2.796616  ]
   [ -5.4420433 ]
   [ -1.759464  ]
   [ -4.450033  ]
   [ -7.869393  ]
   [ -1.1793673 ]
   [  0.19335382

Another Example

In [16]:
input = tf.Variable(tf.random_normal([1,20,20,1]))
filter = tf.Variable(tf.random_normal([4,4,1,1]))

op1 = tf.nn.conv2d(input,filter,strides = [1,1,1,1], padding = "VALID")
op2 = tf.nn.conv2d(input,filter,strides = [1,1,1,1], padding = "SAME")

In [17]:
op1

<tf.Tensor 'Conv2D_4:0' shape=(1, 17, 17, 1) dtype=float32>

In [18]:
op2

<tf.Tensor 'Conv2D_5:0' shape=(1, 20, 20, 1) dtype=float32>

In [19]:
input

<tf.Variable 'Variable_6:0' shape=(1, 20, 20, 1) dtype=float32_ref>

In [20]:
filter

<tf.Variable 'Variable_7:0' shape=(4, 4, 1, 1) dtype=float32_ref>

In [22]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    res_1 = sess.run(op1)
    print(res_1)
    
    res_2 = sess.run(op2)
    print(res_2)

[[[[ 4.4593840e+00]
   [-2.1227331e+00]
   [ 1.9403956e+00]
   [ 1.7045870e+00]
   [ 1.2740195e-01]
   [-1.0407847e-01]
   [ 1.1811802e+00]
   [-6.6360512e+00]
   [-5.7537808e+00]
   [ 4.1945887e-01]
   [-3.3819938e-01]
   [-2.1833310e+00]
   [-5.9605536e+00]
   [-5.5119605e+00]
   [-3.1866664e-01]
   [-6.9712763e+00]
   [-3.9938345e+00]]

  [[-6.1270652e+00]
   [-3.8650603e+00]
   [-2.1147087e+00]
   [ 2.7316992e+00]
   [ 7.8878707e-01]
   [ 5.7666230e+00]
   [-5.6261606e+00]
   [-7.8288193e+00]
   [-4.5487847e+00]
   [-6.1050189e-01]
   [-6.0547404e+00]
   [ 1.1485157e+01]
   [-7.4274263e+00]
   [ 6.5480881e+00]
   [ 6.3951635e+00]
   [-3.3203373e+00]
   [-2.3442082e+00]]

  [[ 4.9187002e+00]
   [ 7.5157654e-01]
   [-5.1444659e+00]
   [-2.5549324e+00]
   [-4.0952225e+00]
   [-1.3065941e+00]
   [ 3.4005930e+00]
   [-5.7122803e+00]
   [ 8.3848077e-01]
   [ 1.0570970e+01]
   [-2.2943769e+00]
   [-3.0825565e+00]
   [ 1.1262119e-01]
   [-1.1591276e+00]
   [ 1.2454073e+00]
   [ 2.5395348e+